spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/testdb03?characterEncoding=utf8
    username: root
    password: system
#    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:h2:~/test
#    driver-class-name: com.mysql.jdbc.Driver
  #    password:


  batch:
    job:
      name: batchjob


server:
  port: 8080

com:
  example:
    demo21032501:
      url: http://localhost:8080
      submit: /submit
      template: /template
      service: /service
      history: /history
      log: /log
      api:
        url: http://tempapi.com/sendLMS?
        result-code:
          success: "00"
      directive:
        column1: phoneNum
        column2: name
        username: $USERNAME
      sessioncookie: tempSSOKey

api:
  manager:
    uri: http://tempauth.com

host:
  manager:
    uri: http://tempauth.com



logging:
  file: logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO
    org.thymeleaf: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.h2.server.web: INFO

